In [3]:
import pandas as pd
import numpy as np
import scipy
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

In [79]:
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [80]:
importances = clf.feature_importances_
importances

array([0., 1.])

In [7]:
np.isnan(X)

array([[False, False],
       [False, False],
       [False, False]])


Загрузите выборку из файла titanic.csv с помощью пакета Pandas.

In [8]:
data = pd.read_csv('titanic.csv')

In [9]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [10]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Оставьте в выборке четыре признака: класс пассажира (Pclass), цену билета (Fare), возраст пассажира (Age) и его пол (Sex).

In [11]:
X = np.array([data['Pclass'], data['Fare'], data['Age'], data['Sex']])

Обратите внимание, что признак Sex имеет строковые значения.
Выделите целевую переменную — она записана в столбце Survived.

In [13]:
Y = np.array([data['Survived']])

В данных есть пропущенные значения — например, для некоторых пассажиров неизвестен их возраст. Такие записи при чтении их в pandas принимают значение nan. Найдите все объекты, у которых есть пропущенные признаки, и удалите их из выборки.

In [19]:
type(X)

numpy.ndarray

In [22]:
X = np.array([data['Pclass'], data['Fare'], data['Age'], data['Sex']])

In [23]:
Y = np.array([data['Survived']])

In [30]:
mapping = {'male': 0, 'female': 1}
data.replace({'Sex': mapping})

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
5                                     Moran, Mr. James    0   NaN      0   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
7                       Palsson, Master. Gosta Leonard    0   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
12                      Saundercock, Mr. William Henry    0  20.0      0   
13                         Andersson, Mr. Anders Johan    0  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina    1  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)     1  55.0      0   
16                                Rice, Master. Eugene    0   2.0      4   
17                        Williams, Mr. Charles Eugene    0   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...    1  31.0      1   
19                             Masselmani, Mrs. Fatima    1   NaN      0   
20                                Fynney, Mr. Joseph

In [33]:
newdata = data.replace({'Sex': mapping})

In [34]:
newdata

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
5                                     Moran, Mr. James    0   NaN      0   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
7                       Palsson, Master. Gosta Leonard    0   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
12                      Saundercock, Mr. William Henry    0  20.0      0   
13                         Andersson, Mr. Anders Johan    0  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina    1  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)     1  55.0      0   
16                                Rice, Master. Eugene    0   2.0      4   
17                        Williams, Mr. Charles Eugene    0   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...    1  31.0      1   
19                             Masselmani, Mrs. Fatima    1   NaN      0   
20                                Fynney, Mr. Joseph

In [64]:
data = newdata.dropna()
data

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
21            22         1       2   
23            24         1       1   
27            28         0       1   
31            32         1       1   
52            53         1       1   
54            55         0       1   
55            56         1       1   
62            63         0       1   
66            67         1       2   
75            76         0       3   
88            89         1       1   
92            93         0       1   
96            97         0       1   
97            98         1       1   
102          103         0       1   
110          111         0       1   
118          119         0       1   
123          124         1       2   
124          125         0       1   
128          129         1       3   
136          137         1       1   
137          138         0       1   
139          140         0       1   
148          149         0       2   
151          152         1       1   
..           ...       ...     ...   
748          749         0       1   
751          752         1       3   
759          760         1       1   
763          764         1       1   
765          766         1       1   
772          773         0       2   
776          777         0       3   
779          780         1       1   
781          782         1       1   
782          783         0       1   
789          790         0       1   
796          797         1       1   
802          803         1       1   
806          807         0       1   
809          810         1       1   
815          816         0       1   
820          821         1       1   
823          824         1       3   
835          836         1       1   
839          840         1       1   
849          850         1       1   
853          854         1       1   
857          858         1       1   
862          863         1       1   
867          868         0       1   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
21                               Beesley, Mr. Lawrence    0  34.0      0   
23                        Sloper, Mr. William Thompson    0  28.0      0   
27                      Fortune, Mr. Charles Alexander    0  19.0      3   
31      Spencer, Mrs. William Augustus (Marie Eugenie)    1   0.0      1   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)    1  49.0      1   
54                      Ostby, Mr. Engelhart Cornelius    0  65.0      0   
55                                   Woolner, Mr. Hugh    0   0.0      0   
62                         Harris, Mr. Henry Birkhardt    0  45.0      1   
66                        Nye, Mrs. (Elizabeth Ramell)    1  29.0      0   
75                             Moen, Mr. Sigurd Hansen    0  25.0      0   
88                          Fortune, Miss. Mabel Helen    1  23.0      3   
92                         Chaffee, Mr. Herbert Fuller    0  46.0      1   
96                           Goldschmidt, Mr. George B    0  71.0      0   
97                     Greenfield, Mr. William Bertram    0  23.0      0   
102                          White, Mr. Richard Frasar    0  21.0      0   
110                     Porter, Mr. Walter Chamberla

Обучите решающее дерево с параметром random_state=241 и остальными параметрами по умолчанию (речь идет о параметрах конструктора DecisionTreeСlassifier).

# Pclass

In [90]:
X = np.array([data['Pclass']])
Y = np.array([data['Survived']])
clf = DecisionTreeClassifier(random_state=241)
clf.fit(X, Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=241,
            splitter='best')

In [82]:
print('====================================\n====================================')
importances = clf.feature_importances_
importances

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Fare

In [92]:
X = np.array([data['Fare']])
Y = np.array([data['Survived']])
clf = DecisionTreeClassifier(random_state=241)
clf.fit(X, Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=241,
            splitter='best')

In [84]:
print('====================================\n====================================')
importances = clf.feature_importances_
importances

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Age

In [94]:
X = np.array([data['Age']])
Y = np.array([data['Survived']])
clf = DecisionTreeClassifier(random_state=241)
clf.fit(X, Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=241,
            splitter='best')

In [86]:
print('====================================\n====================================')
importances = clf.feature_importances_
importances

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Sex

In [96]:
X = np.array([data['Sex']])
Y = np.array([data['Survived']])
clf = DecisionTreeClassifier(random_state=241)
clf.fit(X, Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=241,
            splitter='best')

In [88]:
print('====================================\n====================================')
importances = clf.feature_importances_
importances

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [114]:
df = pd.read_csv('titanic.csv', index_col='PassengerId')
x_labels = ['Pclass', 'Fare', 'Age', 'Sex']
X = df.loc[:, x_labels]
X['Sex'] = X['Sex'].map(lambda sex: 1 if sex == 'male' else 0)
y = df['Survived']
X = X.dropna()
y = y[X.index.values]
clf = DecisionTreeClassifier(random_state=241)
clf.fit(np.array(X.values), np.array(y.values))
importances = pd.Series(clf.feature_importances_, index=x_labels)
print(1, ' '.join(importances.sort_values(ascending=False).head(2).index.values))

1 Fare Sex


In [120]:
X

Pclass      Fare   Age  Sex
PassengerId                             
1                 3    7.2500  22.0    1
2                 1   71.2833  38.0    0
3                 3    7.9250  26.0    0
4                 1   53.1000  35.0    0
5                 3    8.0500  35.0    1
7                 1   51.8625  54.0    1
8                 3   21.0750   2.0    1
9                 3   11.1333  27.0    0
10                2   30.0708  14.0    0
11                3   16.7000   4.0    0
12                1   26.5500  58.0    0
13                3    8.0500  20.0    1
14                3   31.2750  39.0    1
15                3    7.8542  14.0    0
16                2   16.0000  55.0    0
17                3   29.1250   2.0    1
19                3   18.0000  31.0    0
21                2   26.0000  35.0    1
22                2   13.0000  34.0    1
23                3    8.0292  15.0    0
24                1   35.5000  28.0    1
25                3   21.0750   8.0    0
26                3   31.3875  38.0    0
28                1  263.0000  19.0    1
31                1   27.7208  40.0    1
34                2   10.5000  66.0    1
35                1   82.1708  28.0    1
36                1   52.0000  42.0    1
38                3    8.0500  21.0    1
39                3   18.0000  18.0    0
...             ...       ...   ...  ...
857               1  164.8667  45.0    0
858               1   26.5500  51.0    1
859               3   19.2583  24.0    0
861               3   14.1083  41.0    1
862               2   11.5000  21.0    1
863               1   25.9292  48.0    0
865               2   13.0000  24.0    1
866               2   13.0000  42.0    0
867               2   13.8583  27.0    0
868               1   50.4958  31.0    1
870               3   11.1333   4.0    1
871               3    7.8958  26.0    1
872               1   52.5542  47.0    0
873               1    5.0000  33.0    1
874               3    9.0000  47.0    1
875               2   24.0000  28.0    0
876               3    7.2250  15.0    0
877               3    9.8458  20.0    1
878               3    7.8958  19.0    1
880               1   83.1583  56.0    0
881               2   26.0000  25.0    0
882               3    7.8958  33.0    1
883               3   10.5167  22.0    0
884               2   10.5000  28.0    1
885               3    7.0500  25.0    1
886               3   29.1250  39.0    0
887               2   13.0000  27.0    1
888               1   30.0000  19.0    0
890               1   30.0000  26.0    1
891               3    7.7500  32.0    1

[714 rows x 4 columns]

In [121]:
y

PassengerId
1      0
2      1
3      1
4      1
5      0
7      0
8      0
9      1
10     1
11     1
12     1
13     0
14     0
15     0
16     1
17     0
19     0
21     0
22     1
23     1
24     1
25     0
26     1
28     0
31     0
34     0
35     0
36     0
38     0
39     0
      ..
857    1
858    1
859    1
861    0
862    0
863    1
865    0
866    1
867    1
868    0
870    1
871    0
872    1
873    0
874    0
875    1
876    1
877    0
878    0
880    1
881    1
882    0
883    0
884    0
885    0
886    0
887    0
888    1
890    1
891    0
Name: Survived, Length: 714, dtype: int64